### ISSUE TITLE
Consumer-friendly names for USA

### ISSUE THREAD

**Issue by jmandel** [dvci/shc-terminology#1]
@grahamegrieve are you OK if we update to make the US-based names consistent with the "Sale Proprietary Name" values at https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html? And if you are ... let me know if you'd rather I submit a PR or if you want to do this (I'm not sure if you've hand-authored the .JSON file or generated it from another source)

**Comment by grahamegrieve** [comment]
I hand authored that, and github is the master. So changes there. A PR is fine ;-) (or I can do it)
